---
title: "Printing demo"
output: word_document
date: "2026-05-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE}
library(ipeval)
library(survival)
n <- 10000

set.seed(1)
horizon <- 10
n <- 10000
data <- data.frame(
  L = rnorm(n, mean = 0),
  P = rnorm(n, mean = 0)
)
data$my_trt <- rbinom(n, 1, plogis(0.2 + 0.5*data$L))

data$time0 <- ipeval:::simulate_time_to_event(n, 0.04, data$L + 0.5*data$P)
data$time1 <- ipeval:::simulate_time_to_event(n, 0.04, data$L + 0.5*data$P - 0.6)
data$censortime <- ipeval:::simulate_time_to_event(n, 0.04, 0.5*data$L + 0.6*data$P + 0.2*data$my_trt)
data$time_uncensored <- ifelse(data$my_trt == 1, data$time1, data$time0)
data$status_uncensored <- 1

data$status <- ifelse(data$time_uncensored <= data$censortime, TRUE, FALSE)
data$time <- ifelse(data$status == TRUE,
                    data$time_uncensored,
                    data$censortime)

glmmodel <- glm(status ~ my_trt, data = data)

survmodel <- survival::coxph(
  formula = survival::Surv(time, status) ~ P + my_trt,
  data = data
)
```


# binary outcome, simple

```{r}
ip_score <- ip_score(
  data = data,
  object = glmmodel,
  outcome = status,
  treatment_formula = my_trt ~ L,
  treatment_of_interest = 0,
  metrics = "auc"
)
ip_score
```

# survival outcome, KM censoring

```{r}
ip_score <- ip_score(
  data = data,
  object = survmodel,
  outcome = survival::Surv(time, status),
  treatment_formula = my_trt ~ L,
  treatment_of_interest = 0,
  time_horizon = 10,
  metrics = "auc"
)
ip_score
```
# survival outcome, informative cox censoring

```{r}
ip_score <- ip_score(
  data = data,
  object = survmodel,
  outcome = survival::Surv(time, status),
  treatment_formula = my_trt ~ L,
  treatment_of_interest = 0,
  time_horizon = 10,
  metrics = c("auc", "calplot"),
  cens_model = "cox",
  cens_formula = ~ L + P + my_trt,
)
ip_score
```

# manually specifying IPTW & IPCW

```{r}
ip_score <- ip_score(
  data = data,
  object = survmodel,
  outcome = survival::Surv(time, status),
  treatment_formula = my_trt ~ L,
  treatment_of_interest = 0,
  time_horizon = 10,
  metrics = c("auc"),
  iptw = 1/runif(n),
  ipcw = 1/runif(n)
)
ip_score
```
